---
title: "Word2Vec Analysis"
author: "Isaac Scheinfeld"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: default
---
# Networks

This report explores the clustering of nouns aquired by 16 - 30 month old children using word2vec similarity, and the dynamics of those clusters.

```{r echo=FALSE, message=FALSE, warning=FALSE} 
library(purrr) # fp library
library(readr) # read text data files (csv, etc.)
library(ggplot2) # plotting
library(langcog) # useful things used by Language and Cognition Lab
library(dplyr) # for working with datafram-like objects
library(tidyr) # for data tidying
library(wordbankr) # access to wordbank data
library(stringr) # common string operations
library(broom) # converts R function outputs to tidy data frames
library(igraph) # network analysis and visualization
library(knitr) # general-purpose tool for dynamic report generation
library(kableExtra) # table formatting
library(lemon) # functions for working w/ ggplot2 and knitr extensions
library(tibble) # modern dataframes
library(tidygraph)
library(doParallel)
library(networkD3)
library(ForceAtlas2)
library(riverplot) # install from github at ischeinfeld/riverplot to hide debug messages in CRAN package
```

## Random Network

```{r}

```

